default_platform(:android)

platform :android do
  android_dir = ENV["PROJECT_PATH"]

  desc "Assemble debug or release APK"
  lane :assemble do
    gradle(task: 'clean', project_dir: android_dir)
    gradle(
      task: ENV["GRADLE_TASK"],
      project_dir: android_dir,
      flags: "--no-daemon",
    )

    APK_LOCATION = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    sh("cp", "#{APK_LOCATION}", ENV["OUTPUT_PATH"])
  end

  desc "Bundle signed release AAB"
  lane :bundle do
    puts "Gradle task: #{ENV["GRADLE_TASK"]}"
    sh("ls", "-la", "..")
    sh("ls", "-la")

    gradle(task: 'clean', project_dir: android_dir)
    gradle(
      task: ENV["GRADLE_TASK"],
      project_dir: android_dir,
      flags: "--no-daemon",
      properties: {
        "android.injected.signing.store.file" => File.join(Dir.pwd, "..", ENV["KEYSTORE_FILE_PATH"]),
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_PASSWORD"],
      }
    )

    AAB_LOCATION = "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
    sh("cp", "#{AAB_LOCATION}", ENV["OUTPUT_PATH"])
  end
end