name: Test Building Android App
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CAPACITOR_APP_DIR: testing/test-capacitor-app
jobs:
  test-android-bundle-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: cd ${{env.CAPACITOR_APP_DIR}} && npm ci && cd -
      - name: Create build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: cd ${{env.CAPACITOR_APP_DIR}} && npm run build && cd -
      - name: Sync with Capacitor
        run: cd ${{env.CAPACITOR_APP_DIR}} && npx cap sync && cd -
        # if using local testing (nektos/act), need to set up Android SDK
      - name: Set up Android SDK
        if: ${{ github.event.act }}
        uses: android-actions/setup-android@v2
      - uses: ./
        id: android-bundle-release
        with:
          build-type: bundle
          ruby-version: "3.3.0"
          project-path: ${{env.CAPACITOR_APP_DIR}}/android
          gradle-task: bundleRelease
          node-version: "20.11.0"
          fastlane-version: "2.219.0"
          bundler-version: "2.5.5"
          keystore-content: ${{ secrets.CAP_APP_KEYSTORE_CONTENT }}
          keystore-password: ${{ secrets.CAP_APP_KEYSTORE_PASSWORD }}
          keystore-alias: ${{ secrets.CAP_APP_KEYSTORE_ALIAS }}
          output-path: test-capacitor-app.aab
  test-android-assemble-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: cd ${{env.CAPACITOR_APP_DIR}} && npm ci && cd -
      - name: Create build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: cd ${{env.CAPACITOR_APP_DIR}} && npm run build && cd -
      - name: Sync with Capacitor
        run: cd ${{env.CAPACITOR_APP_DIR}} && npx cap sync && cd -
        # if using local testing (nektos/act), need to set up Android SDK
      - name: Set up Android SDK
        if: ${{ github.event.act }}
        uses: android-actions/setup-android@v2
      - uses: ./
        id: android-assemble-debug
        with:
          build-type: assemble
          ruby-version: "3.3.0"
          project-path: ${{env.CAPACITOR_APP_DIR}}/android
          gradle-task: assembleDebug
          node-version: "20.11.0"
          fastlane-version: "2.219.0"
          bundler-version: "2.5.5"
          output-path: test-capacitor-app.apk
