name: Test Building Android App

on:
  workflow_dispatch:

jobs:
  test-android-bundle-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: cd hakubun && npm ci && cd ..
      - name: Create build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: cd hakubun && npm run build && cd ..
      - name: Sync with Capacitor
        run: cd hakubun && npx cap sync && cd ..
      # TODO: check whether using act or not, don't need this step if not locally testing w act
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
      - uses: ./
        id: android-bundle-release
        with:
          build-type: bundle
          ruby-version: "3.3.0"
          project-path: hakubun/android
          gradle-task: bundleRelease
          node-version: "20.11.0"
          fastlane-version: "2.219.0"
          bundler-version: "2.5.5"
          keystore-content: ${{ secrets.KEYSTORE_CONTENT }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          keystore-alias: ${{ secrets.KEYSTORE_ALIAS }}
          output-path: hakubun.aab
